version: '2'

services:
  httpd:
    container_name: httpd-container
    build: ./docker/httpd
    ports:
      - "80:80"
  tomcat:
    container_name: tomcat-container
    build: ./docker/tomcat
    volumes:
      - ./target/ROOT.war:/Users/danyelsanches/Documents/projetos/workspace_java/project-web/target/demo-0.0.1-SNAPSHOT.war
    expose:
      - "8009"